#!/usr/bin/env python3
"""Builds src/domain_words.inc from the word lists in tools/domains/.

Each list is plain text, one or more words per line, '#' starts a comment.
English words are lower-cased and must be letters only (3+ letters: shorter
tokens are handled by the curated short-word lists in core.c). Persian words
are normalised (Arabic yeh/kaf to Persian, ZWNJ removed, as the base
dictionary stores them) and must be Persian letters only.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PERSIAN_LETTERS = set("ابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیآئؤأإء")

PACKS = [
    # (C identifier, title, english list, persian list)
    ("it", "IT and computing", "tools/domains/it-en.txt", "tools/domains/it-fa.txt"),
]


def words_of(path):
    for line in (ROOT / path).read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0]
        for word in line.split():
            yield word


def english(path):
    result = set()
    for word in words_of(path):
        word = word.lower()
        if not re.fullmatch(r"[a-z]+", word):
            sys.exit(f"{path}: not a letters-only English word: {word!r}")
        if len(word) >= 3:
            result.add(word)
    return sorted(result)


def persian(path):
    result = set()
    for word in words_of(path):
        word = word.replace("ي", "ی").replace("ك", "ک").replace("‌", "")
        if not word or any(c not in PERSIAN_LETTERS for c in word):
            sys.exit(f"{path}: not a Persian letters-only word: {word!r}")
        if len(word) >= 3:
            result.add(word)
    return sorted(result)


def c_array(name, words):
    lines = [f"static const wchar_t *const {name}[] = {{"]
    for word in words:
        escaped = "".join(c if ord(c) < 128 else f"\\x{ord(c):04X}" for c in word)
        # A hex escape followed by a hex digit would merge; split the literal.
        escaped = re.sub(r"(\\x[0-9A-F]{4})(?=[0-9A-Fa-f])", r'\1" L"', escaped)
        lines.append(f'    L"{escaped}",')
    lines.append("};")
    return "\n".join(lines)


def main():
    out = ["/* Generated by tools/generate_domain_words.py from tools/domains/. Do not edit. */", ""]
    for ident, title, en_path, fa_path in PACKS:
        en = english(en_path)
        fa = persian(fa_path)
        out.append(f"/* {title}: {len(en)} English, {len(fa)} Persian words. */")
        out.append(c_array(f"DOMAIN_{ident.upper()}_EN", en))
        out.append(c_array(f"DOMAIN_{ident.upper()}_FA", fa))
        out.append("")
        print(f"{title}: {len(en)} English, {len(fa)} Persian")
    (ROOT / "src/domain_words.inc").write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
